### ISSUE TITLE
@bit/bit.javascript.component.id package throwing 401

### ISSUE THREAD

**Issue by kmhari** [teambit/evangelist#2]
Bit is installed and logged in.
Tried npm install and yarn install

Both resulting in 404 errors on pacakge @bit/bit.javascript.component.id

Yarn
Couldn't find package "@bit/bit.javascript.component.id" on the "npm" registry.

NPM
npm ERR! 401 Unauthorized - GET https://node.bit.dev/@bit%2fbit.javascript.component.id

**Comment by itaymendel** [comment]
Hi @kmhari , where did you get this component name?
What are you trying to install that causes this error?

**Comment by KutnerUri** [comment]
Hey @kmhari ! The scope had been accidentally made private, I changed it back to public.
Please try again :)
